### PR TITLE
Updating type script date format

### PR DESCRIPTION
**Pull request by jacob-kinzer**
Updating typescript for the graphs to pass back the date in the correct formatting using iso8601 which should guarantee an 2 digit format for month and day.

In reference to [https://github.com/tmobile/pacbot/issues/117](https://github.com/tmobile/pacbot/issues/117)

Sidenote: I am by no means an expert in JS/TS so any feedback is welcome.

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-390

### CODE REVIEW

**Comment by adiagrwl94** [comment]
This will be taken care by PR #118 by dmpl1 to dev, which will eventually go to master, thank you.

**Comment by adiagrwl94** [comment]
@jacob-kinzer Feedback: The javascript prevDate.setMonth(prevDate.getMonth() - 1); will take care even if month is January. You wouldn't need to explicitly handle it by setting one month back as December and of previous year. This is handled by the setMonth itself!

**Comment by jacob-kinzer** [comment]
> @jacob-kinzer Feedback: The javascript prevDate.setMonth(prevDate.getMonth() - 1); will take care even if month is January. You wouldn't need to explicitly handle it by setting one month back as December and of previous year. This is handled by the setMonth itself!

Sorry do you mean like https://github.com/tmobile/pacbot/blob/98968b98ca5741b4d70168dcb0a25c9c92912d5d/webapp/src/app/pacman-features/secondary-components/certificate-assets-trend/certificate-assets-trend.component.ts#L118 ? During my testing it seemed like the backend API was expecting the date to be a month back, otherwise if i did not set it a month back the graphs were only show _today_ - _today_, if that makes sense. Let me know if i misunderstood what you were referencing though.

**Comment by adiagrwl94** [comment]
@jacob-kinzer What I mean to say is in:

if (today.getMonth() === 0) { // No need to handle this
            today.setFullYear(today.getFullYear() - 1); // not required
            today.setMonth(11); // not required
            fromDay = today.toISOString().substring(0, 10);
}

The else { today.setMonth(today.getMonth() - 1); fromDay = today.toISOString().substring(0, 10); } will take care of getMonth() == 0 (January) too. The JS takes January minus one month as December of Previous year in setDate()!

**Comment by jacob-kinzer** [comment]
Sorry i wasnt able to get back to you faster work has been busy. I am not sure if this PR is needed anymore. It looks like there is a commit in the 1.2 branch that should handle this use case:

https://github.com/tmobile/pacbot/pull/131/commits/3ca755c34940ef34f5125763aca9df5ae3cb4ddd

If this PR is still needed i can update it otherwise i think it can be closed.

**Comment by adiagrwl94** [comment]
@jacob-kinzer  We would still be looking forward for this PR and requested change to be made as this is to master branch. Please do remove the redundant separate handling of getMonth() === 0 as this is not required as an if-else loop. Thanks.

Example: 
const dateToday = new Date('2019-01-03'); // January
let earlierDate = new Date(dateToday)
earlierDate.setMonth(dateToday.getMonth() - 1); // One month before January
earlierDate = earlierDate.toISOString().substring(0, 10);
console.log(earlierDate); // December of previous year (2018-12-03)

**Pull request closed without merging**
